### PR TITLE
bam2hints optimizations

### PR DESCRIPTION
**Pull request by nathanweeks**
A colleague observed that bam2hints had extremely-long runtime (job script timed out after 7 days of execution) when processing his 22 GB BAM file containing alignments against a reference comprising 13 large-ish chromosomes, the largest clocking in a > 300Mb, and > 100K scaffolds. Running bam2hints with Intel VTune Profiler revealed that most of the runtime was spent in [this loop](https://github.com/Gaius-Augustus/Augustus/blob/ab073ef0723d0ed4e83fb5f2051d3dd47372d551/auxprogs/bam2hints/bam2hints.cc#L840), which sets all elements of an alignment coverage array to 0.

Since this code isn't used when the -C/--max-coverage option isn't specified, this PR suggests conditionally executing that code only when -C/--max-coverage is specified with an option-argument > 0.
This resulted in a profound speedup for bam2hints on the aforementioned BAM file (from not completing after 7 days to finishing in under 20 minutes).

Additionally, the performance when -C/--max-coverage is specified could be improved by at least a factor of 4 (on the target system) by only allocating memory for the alignment coverage array once, instead of allocating/deallocating repeatedly. Running bam2hints through a debugger, it appeared that the code that determined the maximum reference sequence length using the bamtools API wasn't obtaining the desired result; this PR also attempts to fix that (though perhaps not in the most succinct idiomatic C++?), allowing an alignment coverage array large enough to handle all reference sequences in the BAM file to be allocated once.

### CODE REVIEW

**Comment by nathanweeks** [comment]
I'll add that older versions of GCC (e.g., the default gcc 4.8.5 on CentOS 7.x hosts) don't vectorize at optimization level -O2, so it might be worth either bumping up the optimization level in the Makefile to -O3, or replacing:
```
// initialize the coverage with zeros
for(CovIter = 0; CovIter < CovBinCount; CovIter++)
{
    alnCoverage[CovIter] = 0;
}
``` 
with the equivalent memset(), which tends to be optimized; e.g.:
```
memset(alnCoverage, 0, CovBinCount*sizeof(alnCoverage[0]));
```

**Review by MarioStanke — APPROVED** [review]
Great work. Indeed, besides the inefficiency, the initialization of maxCovBins was wrong, which likely has led to hardly any filtering of reads that exceeded the maximum coverage (if the option was  used). It probably was introduced when this was converted from the older psl2hints.

**Comment by MarioStanke** [comment]
Thanks a lot, again, Nathan.

**Comment by xiekunwhy** [comment]
Hi,

It cost me 5 hours to run bam2hints for a 40Gb bam file (-C 2000 --intronsonly), and the genome size is 64M with 24 contigs.
Is it normal, and is there a multiple thread version of bam2hints ?

Best,
kun

**Comment by MarioStanke** [comment]
In BRAKER we don't run `bam2hints` with the option   `-C`. I suggest you try whether this speeds it up.

**Pull request merged**
