### PR TITLE
Json parameters

### PR DESCRIPTION
**Pull request by dhonsel**
Use JSON configuration file to check allowed command line parameters.

### CODE REVIEW

**Review by MarioStanke — CHANGES_REQUESTED** [review]
The manual override of the parameters in the config file does not work anymore.
For example:
`augustus --species=human examples/example.fa --exonnames=1`
is supposed to generate lines like this:
`HS08198 AUGUSTUS        internal        1053    1123    .       +       1       transcript_id "g2.t1"; gene_id "g2";`
as it does in the master branch. Some parameters specified on the command line are ignored, another example is `--sample=33`.

A likely reason is that the code block starting in properties.cc:489 was deleted:

// read in the other parameters, command line parameters have higher priority
// than those in the config files

**Comment by dhonsel** [comment]
> The manual override of the parameters in the config file does not work anymore.
> For example:
> `augustus --species=human examples/example.fa --exonnames=1`
> is supposed to generate lines like this:
> `HS08198 AUGUSTUS internal 1053 1123 . + 1 transcript_id "g2.t1"; gene_id "g2";`
> as it does in the master branch. Some parameters specified on the command line are ignored, another example is `--sample=33`.
> 
> A likely reason is that the code block starting in properties.cc:489 was deleted:
> 
> // read in the other parameters, command line parameters have higher priority
> // than those in the config files

Thanks for the feedback. I'll try to fix the problem.

**Comment by dhonsel** [comment]
Manual overwriting of preconfigured parameters should now work again.

**Comment by MarioStanke** [comment]
Yes, what I tested works. I will merge..

**Review by MarioStanke — APPROVED** [review]

**Pull request merged**
