### PR TITLE
Revised the tutorial for the current programs

### PR DESCRIPTION
**Pull request by Steinedieb**
The tutorial (all HTML files and the CSS file) have been modified according to the current synopsis of the needed programs. Especially, the instructions for Progressive Cactus have been revised. Partially, instructions for Singularity containers have been added. All files have been formatted to be better readable and validated to conform with HTML5.

### CODE REVIEW

**Review by MarioStanke — CHANGES_REQUESTED** [review]
Thanks for updating this. However, most changes are without effect on what the users see, such as indentation and line breaks and it takes a long time to see what the actual important changes are. Probably this was done automatically by the editor you used.
Can you please update the pull request to only the important changes, which change what a viewer sees? 
HTML indentation and line breaks are rather a matter of taste. If one intentionally wanted to improve the layout, one would rather do two commits, e.g. "content changed", "only formatting changed". Then a reviewer can look at individual commits.
As a rule of thumb, though, rarely change the formatting of whole files.

**Comment by Steinedieb** [comment]
I now have reverted the layout of all files back to the original one, such that only the changes on the bash code and the transition from HTML 4.01 to HTML5 should remain.

**Review by MarioStanke — CHANGES_REQUESTED** [review]
The file
`docs/tutorial-cgp/index.html`
is not rendered OK in chrome, firefox and konqueror:
The text "CGP (comparative gene prediction) is ..." is displayed in a very narrow column.

**Comment by Steinedieb** [comment]
The error was that I set exact values in px for the images' width to deal with the apparently invalid percentage signs. However, I now realized that the relative scaling of images by percentage signs appears to be only invalid in HTML, not in CSS (probably owing to the strict separation between markup (HTML), style (CSS) and behavior (JavaScript)). Therefore, I turned these scaling factors into proper CSS classes. Now, the images are scaled as in the published HTML files with the same factors while keeping all files valid.

**Review by MarioStanke — APPROVED** [review]
Very good work!

**Pull request merged**
